name: rest_data
description: Easily interact with REST APIs without dealing with HTTP and JSON
version: 1.0.0
homepage: https://www.algonauti.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  http: ^0.13.3

dev_dependencies:
  test: ^1.17.9
